version: "3.0"
services:
  rabbitmq:
    platform: linux/amd64
    image: rabbitmq:management
    container_name: rabbitmq
    
  dft-service-ui:
    platform: linux/amd64
    image: dgbtechnologies/dft-service-ui:latest
    container_name: dft-service-ui
    ports:
      - 8080:8080

  dft-service-api:
    platform: linux/amd64
    image: dgbtechnologies/dft-service-api:latest
    container_name: dft-service-api
    volumes:
      - ./projects:/home/projects
    environment:
      STORMPY_SERVICE_HOST: stormpy-service-api
      STORMPY_SERVICE_PORT: 8001

  stormpy-service-api:
    platform: linux/amd64
    image: dgbtechnologies/stormpy-service-api:latest
    container_name: stormpy-service-api
    environment:
      RMQ_USERNAME: guest
      RMQ_PASSWORD: guest
      RMQ_VHOST: auto_task
      RMQ_HOST: rabbitmq
      RMQ_PORT: 5672
      RMQ_VERIFICATION_QUEUE: verification
      RMQ_EXPERIMENT_QUEUE: experiment
      RMQ_APPROAXIMATION_QUEUE: approximation