services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 15674:15674
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    restart: always
  
  mysql:
    image: mysql:8.0-bookworm
    platform: linux/amd64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: safest  # Create a default database named 'safest'
    ports:
      - 3307:3306  # Expose MySQL on port 3306
    volumes:
      - ./mysql-db:/var/lib/mysql
    restart: always

  stormpy-service-api:
    platform: linux/amd64
    image: dgbtechnologies/stormpy-service-api:latest
    container_name: stormpy-service-api
    ports:
      - 8001:8001
    environment:
      COMPUTE_SYMMETRIES: COMPUTE_SYMMETRIES_YES
    restart: always

  dft-service-api:
    platform: linux/amd64
    image: dgbtechnologies/dft-service-api:latest
    container_name: dft-service-api
    ports:
      - 8000:8000
    volumes:
      - ./projects:/home/project_files
    environment:
      RMQ_USERNAME: guest
      RMQ_PASSWORD: guest
      RMQ_VHOST: auto_task
      RMQ_HOST: rabbitmq
      RMQ_PORT: 5672
      RMQ_MANAGEMENT_PORT: 15672
      RMQ_VERIFICATION_QUEUE: verification
      RMQ_EXPERIMENT_QUEUE: experiment
      RMQ_BOUNDED_VERIFICATION_QUEUE: bounded
      RMQ_EVENT_TREE_ANALYSIS_QUEUE: ETA
      ANALYSIS_LOGS: ANALYSIS_LOGS_YES
      STORMPY_SERVICE_HOST: stormpy-service-api
      STORMPY_SERVICE_PORT: 8001
      PROJECT_FILES: /home/project_files/
      MYSQL_USERNAME : root
      MYSQL_PASSWORD : root
      MYSQL_HOST : host.docker.internal
      MYSQL_PORT : 3307
      MYSQL_DATABASE: safest
    restart: always
    depends_on:
      - mysql
    
  dft-service-ui:
    platform: linux/amd64
    image: dgbtechnologies/dft-service-ui:latest
    container_name: dft-service-ui
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - dft-service-api

  