version: "3.0"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 15674:15674
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    restart: always

  stormpy-service-api:
    platform: linux/amd64
    image: dgbtechnologies/stormpy-service-api:latest
    container_name: stormpy-service-api
    ports:
      - 8001:8001
    environment:
      COMPUTE_SYMMETRIES: COMPUTE_SYMMETRIES_YES
    restart: always

  dft-service-api:
    platform: linux/amd64
    image: dgbtechnologies/dft-service-api:latest
    container_name: dft-service-api
    ports:
      - 8000:8000
    volumes:
      - ./projects:/home/projects
    environment:
      RMQ_USERNAME: guest
      RMQ_PASSWORD: guest
      RMQ_VHOST: auto_task
      RMQ_HOST: rabbitmq
      RMQ_PORT: 5672
      RMQ_VERIFICATION_QUEUE: verification
      RMQ_EXPERIMENT_QUEUE: experiment
      RMQ_BOUNDED_VERIFICATION_QUEUE: bounded
      RMQ_EVENT_TREE_ANALYSIS_QUEUE: ETA
      ANALYSIS_LOGS: ANALYSIS_LOGS_YES
      STORMPY_SERVICE_HOST: stormpy-service-api
      STORMPY_SERVICE_PORT: 8001
      BACKUP_FOLDER: /home/projects/
    restart: always
    
  dft-service-ui:
    platform: linux/amd64
    image: dgbtechnologies/dft-service-ui:latest
    container_name: dft-service-ui
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - dft-service-api